# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]  # main 브랜치에 푸시될 때 실행
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (필요한 경우, Node.js로 빌드되는 프로젝트인 경우)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 프로젝트에서 사용하는 Node.js 버전

      - name: Install dependencies and build (필요한 경우, 빌드를 실행해야 할 경우)
        run: |
          npm install
          npm run build  # 프로젝트 빌드 명령어

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # 빌드된 파일이 위치한 폴더 (예: ./dist, ./public 등)


